# Generated by Django 2.1.7 on 2019-08-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upld', '0003_auto_20190810_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubproject',
            name='local_git_repo',
            field=models.FilePathField(default='C:\\Users\\rishi\\Google Drive\\Django_dir\\PiUpld\\PiUpld/media/uploads'),
        ),
        migrations.AlterField(
            model_name='githubproject',
            name='git_link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='githubproject',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
