# Generated by Django 2.1.7 on 2019-08-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upld', '0004_auto_20190810_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubproject',
            name='local_git_repo',
            field=models.FilePathField(allow_folders=True, default='C:\\Users\\rishi\\Google Drive\\Django_dir\\PiUpld\\PiUpld/media/uploads'),
        ),
    ]
